INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (1, 'Alya Sometimes Hides Her Feelings in Russian', 'Shelf A-17', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (2, 'Atomic Habits', 'Shelf A-25', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (3, 'Before the Coffee Gets Cold', 'Shelf B-5', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (4, 'Before Your Memory Fades', 'Shelf B-6', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (5, 'Black Ghost', 'Shelf B-19', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (6, 'Cullen\'s Angel', 'Shelf C-2', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (7, 'Haunted Mansion', 'Shelf H-5', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (8, 'Hazrael', 'Shelf H-10', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (9, 'Heaven Official\'s Blessing', 'Shelf H-22', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (10, 'Her Fighter', 'Shelf H-25', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (11, 'His Remedy', 'Shelf H-26', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (12, 'His Secret Side', 'Shelf H-28', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (13, 'I Am A Thief', 'Shelf I-2', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (14, 'I Had That Same Dream Again', 'Shelf I-4', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (15, 'Lockdown Moment', 'Shelf I-7', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (16, 'Mi Esposa', 'Shelf M-1', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (17, 'No Longer Human', 'Shelf N-11', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (18, 'Red, While and Royal Blue', 'Shelf R-3', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (19, 'Stars of Chaos', 'Shelf S-8', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (20, 'The Angel Next Door Spoils Me Rotten', 'Shelf T-9', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (21, 'The Girl Who Drank the Moon', 'Shelf T-11', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (22, 'The Mountain Is You', 'Shelf T-15', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (23, 'The Tunnel To Summer The Exit Of Goodbyes', 'Shelf T-20', 'Borrowed');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (24, 'Unbox', 'Shelf U-12', 'Available');
INSERT INTO `book` (`id`, `book`, `location`, `status`) VALUES (25, 'When Breath Becomes Air', 'Shelf W-7', 'Available');
